Online_App_store/Pages/Admin.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Online_App_store.models;
using System.Collections.Generic;
using System.Data.SqlClient;

namespace Online_App_store.Pages
{
    public class AdminModel : PageModel
    {
        public List<users> Users { get; set; }

        [BindProperty]
        public int UserId { get; set; }
        [BindProperty]
        public string UserType { get; set; }

        public void OnGet()
        {
            LoadUsers();
        }

        public IActionResult OnPostDelete(int userId)
        {
            DeleteUser(userId);
            LoadUsers();
            return Page();
        }

        public IActionResult OnPostUpdateType(int userId, string userType)
        {
            UpdateUserType(userId, userType);
            LoadUsers();
            return Page();
        }

        private void LoadUsers()
        {
            Users = new List<users>();
            string connectionString = "Data Source=laptop-oh72tn5u;Initial Catalog=OnlineAppStore;Integrated Security=True";

            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                connection.Open();
                string sql = "SELECT Id, Email, UserName, Type, PhoneNumber FROM Users";  // Ensure these columns exist in your database
                using (SqlCommand command = new SqlCommand(sql, connection))
                {
                    using (SqlDataReader reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            Users.Add(new users
                            {
                                Id = reader.GetInt32(0),
                                Email = reader.GetString(1),
                                Name = reader.GetString(2),
                                Type = reader.GetString(3),
                                PhoneNumber = reader.GetInt32(4)
                            });
                        }
                    }
                }
            }
        }

        private void DeleteUser(int userId)
        {
            string connectionString = "Data Source=laptop-oh72tn5u;Initial Catalog=OnlineAppStore;Integrated Security=True";
            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                connection.Open();
                string sql = "DELETE FROM Users WHERE Id = @UserId";
                using (SqlCommand command = new SqlCommand(sql, connection))
                {
                    command.Parameters.AddWithValue("@UserId", userId);
                    command.ExecuteNonQuery();
                }
            }
        }

        private void UpdateUserType(int userId, string userType)
        {
            string connectionString = "Data Source=laptop-oh72tn5u;Initial Catalog=OnlineAppStore;Integrated Security=True";
            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                connection.Open();
                string sql = "UPDATE Users SET Type = @UserType WHERE Id = @UserId";
                using (SqlCommand command = new SqlCommand(sql, connection))
                {
                    command.Parameters.AddWithValue("@UserId", userId);
                    command.Parameters.AddWithValue("@UserType", userType);
                    command.ExecuteNonQuery();
                }
            }
        }
    }
}

Online_App_store/Pages/Customer.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Online_App_store.models;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.IO;

namespace Online_App_store.Pages
{
    public class CustomerModel : PageModel
    {
        public List<App> Apps { get; set; }

        public void OnGet()
        {
            LoadApps();
        }

        public IActionResult OnGetDownload(string fileName)
        {
            if (string.IsNullOrEmpty(fileName))
            {
                return NotFound();
            }

            var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "uploads", fileName);
            if (!System.IO.File.Exists(filePath))
            {
                return NotFound();
            }

            var mimeType = "application/octet-stream";
            var fileBytes = System.IO.File.ReadAllBytes(filePath);
            return File(fileBytes, mimeType, Path.GetFileName(filePath));
        }

        private void LoadApps()
        {
            Apps = new List<App>();

            string connectionString = "Data Source=laptop-oh72tn5u;Initial Catalog=OnlineAppStore;Integrated Security=True";
            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                connection.Open();
                string sql = "SELECT AppName, DevName, Type, AppFile FROM Apps";
                using (SqlCommand command = new SqlCommand(sql, connection))
                {
                    using (SqlDataReader reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            Apps.Add(new App
                            {
                                AppName = reader.GetString(0),
                                DevName = reader.GetString(1),
                                Type = reader.GetString(2),
                                AppFile = reader.GetString(3)
                            });
                        }
                    }
                }
            }
        }
    }
}

Online_App_store/Pages/Developer.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Online_App_store.models;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.IO;
using System.Threading.Tasks;

namespace Online_App_store.Pages
{
    public class DeveloperModel : PageModel
    {
        [BindProperty]
        public App App { get; set; }

        public List<App> AppList { get; set; } = new List<App>();

        private readonly string connectionString = "Data Source=laptop-oh72tn5u; Initial Catalog = OnlineAppStore; Integrated Security = True";

        public void OnGet()
        {
            LoadApps();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                LoadApps();
                return Page();
            }

            if (App.UploadedFile != null)
            {
                var filePath = Path.Combine("wwwroot/uploads", App.UploadedFile.FileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    await App.UploadedFile.CopyToAsync(fileStream);
                }
                App.AppFile = "/uploads/" + App.UploadedFile.FileName;
            }

            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                connection.Open();
                string sql = "INSERT INTO Apps (AppName, DevName, Type, AppFile) VALUES (@AppName, @DevName, @Type, @AppFile)";
                using (SqlCommand command = new SqlCommand(sql, connection))
                {
                    command.Parameters.AddWithValue("@AppName", App.AppName);
                    command.Parameters.AddWithValue("@DevName", App.DevName);
                    command.Parameters.AddWithValue("@Type", App.Type);
                    command.Parameters.AddWithValue("@AppFile", App.AppFile);
                    command.ExecuteNonQuery();
                }
            }

            return RedirectToPage();
        }

        public IActionResult OnPostDelete(int id)
        {
            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                connection.Open();
                string sql = "DELETE FROM Apps WHERE Id = @Id";
                using (SqlCommand command = new SqlCommand(sql, connection))
                {
                    command.Parameters.AddWithValue("@Id", id);
                    command.ExecuteNonQuery();
                }
            }

            return RedirectToPage();
        }

        private void LoadApps()
        {
            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                connection.Open();
                string sql = "SELECT Id, AppName, DevName, Type, AppFile FROM Apps";
                using (SqlCommand command = new SqlCommand(sql, connection))
                {
                    using (SqlDataReader reader = command.ExecuteReader())
                    {
                        AppList.Clear();
                        while (reader.Read())
                        {
                            AppList.Add(new App
                            {
                                Id = reader.GetInt32(0),
                                AppName = reader.GetString(1),
                                DevName = reader.GetString(2),
                                Type = reader.GetString(3),
                                AppFile = reader.GetString(4)
                            });
                        }
                    }
                }
            }
        }
    }
}

Online_App_store/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace Online_App_store.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Online_App_store/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Online_App_store.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

Online_App_store/Pages/Login.cshtml.cs
using System;
using System.Data;
using System.Data.SqlClient;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Online_App_store.models;

namespace Online_App_store.Pages
{

    [BindProperties(SupportsGet = true)]
    public class LoginModel : PageModel
    {
        [BindProperty]
        public new required models.users User { get; set; }

        public required string ErrorMessage { get; set; }

        public IActionResult OnPost()
        {
            // Connect to the database
            string connectionString = "Data Source=laptop-oh72tn5u; Initial Catalog = OnlineAppStore; Integrated Security = True";
            SqlConnection con = new SqlConnection();
            {
                con.ConnectionString = connectionString;

                // Query the database to check if the user credentials match
                string query = $"SELECT * FROM users WHERE Password={User.Password}";
                string queryType = $"SELECT Type FROM users WHERE Password={User.Password}";
                SqlCommand command = new SqlCommand(query, con);
                SqlCommand Getype = new SqlCommand(queryType, con);
                DataTable dt = new DataTable();

                try
                {
                    con.Open();
                    dt.Load(command.ExecuteReader());
                    User.Type = (string)Getype.ExecuteScalar();
                    if (dt.Rows.Count >= 0)
                    {
                        if (User.Type == "developer")
                        {
                            return RedirectToPage("/Developer");
                        }
                        if (User.Type == "customer")
                        {
                            return RedirectToPage("/Customer");
                        }
                        if (User.Type == "admin")
                        {
                            return RedirectToPage("/admin");
                        }

                    }
                    else
                    {
                        // User credentials do not match, display an error message
                        ErrorMessage = "Invalid credentials. Please try again.";                    
                        return RedirectToPage("/Index");
                    }



                }
                catch (SqlException err)
                {
                    Console.WriteLine(err.Message);
                }
                finally
                {
                    con.Close();
                }


            }

            return Page();
        }
        public void OnGet()
        {

        }
    }
}

Online_App_store/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Online_App_store.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Online_App_store/Pages/Profile.cshtml.cs
using System;
using System.Data;
using System.Data.SqlClient;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Online_App_store.models;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory.Database;

namespace Online_App_store.Pages
{
    public class ProfileModel : PageModel
    {
        public string Email { get; set; }
        [BindProperty]
        public new required models.users User { get; set; }

        string connectionString = "Data Source=laptop-oh72tn5u; Initial Catalog = OnlineAppStore; Integrated Security = True";

        public void OnGet()
        {
            string userEmail = "ahmed@hotmail.com";

            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                string sqlQuery = "SELECT Email, Password, UserName, Type, PhoneNumber FROM Users WHERE Email = @Email";

                SqlCommand command = new SqlCommand(sqlQuery, connection);
                command.Parameters.AddWithValue("@Email", userEmail);

                connection.Open();

                SqlDataReader reader = command.ExecuteReader();

                if (reader.Read())
                {
                    User.Email = reader["Email"].ToString();
                    User.Password = reader["Password"] as int?;
                    User.Name = reader["UserName"].ToString();
                    User.Type = reader["Type"].ToString();
                    User.PhoneNumber = reader["PhoneNumber"] as int?;
                }
                reader.Close();
            }
        }
    }
}

Online_App_store/Pages/SignUp.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Online_App_store.models;
using System;
using System.Data.SqlClient;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace Online_App_store.Pages
{


    [BindProperties(SupportsGet = true)]
    public class SignUpModel : PageModel
    {
        [BindProperty]
        public new required models.users User { get; set; }
        [BindProperty]
        public required string tempData { get; set; }
        public required string ErrorMessage { get; set; }


        public IActionResult OnPost()
        {
            string connectionString = "Data Source=laptop-oh72tn5u; Initial Catalog = OnlineAppStore; Integrated Security = True";
            using (SqlConnection con = new SqlConnection(connectionString))
            {
                // Insert the user data into the database
                string query = $"insert into Users (UserName, Email, Password, PhoneNumber, Type) " +
               $"values('{User.Name}', '{User.Email}', '{User.Password}', '{User.PhoneNumber}', '{User.Type}')";

                SqlCommand command = new SqlCommand(query, con);

                try
                {
                    con.Open();
                    command.ExecuteNonQuery();

                    return RedirectToPage("/Login");


                }
                catch (SqlException err)
                {
                    Console.WriteLine(err.Message);
                }
                finally
                {
                    con.Close();
                }

                return Page();

            }

        }
        public void OnGet()
        {

        }
    }
}

Online_App_store/Pages/Admin.cshtml
@page
@model Online_App_store.Pages.AdminModel
@{
    Layout = "Admin_Layout";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin - Manage Users</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <div class="container mt-5">
        <h2>Manage Users</h2>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Email</th>
                    <th>Name</th>
                    <th>Type</th>
                    <th>Phone Number</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var user in Model.Users)
                {
                    <tr>
                        <td>@user.Email</td>
                        <td>@user.Name</td>
                        <td>@user.Type</td>
                        <td>@user.PhoneNumber</td>
                        <td>
                            <form method="post">
                                <input type="hidden" name="userId" value="@user.Id" />
                                <button type="submit" asp-page-handler="Delete" class="btn btn-danger">Delete</button>
                            </form>
                            <form method="post" class="mt-2">
                                <input type="hidden" name="userId" value="@user.Id" />
                                <select name="userType" class="form-control">
                                    <option value="Admin" selected="@user.Type == " Admin"">Admin</option>
                                    <option value="Custmer" selected="@user.Type == " User"">Custmer</option>
                                    <option value="Developer" selected="@user.Type == " User"">Developer</option>
                                </select>
                                <button type="submit" asp-page-handler="UpdateType" class="btn btn-primary mt-2">Update Type</button>
                            </form>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</body>
</html>

Online_App_store/Pages/Customer.cshtml
@page
@model Online_App_store.Pages.CustomerModel
@{
    Layout = "Custumer_Layout";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>App List</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <div class="container mt-5">
        <h2>App List</h2>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>App Name</th>
                    <th>Developer Name</th>
                    <th>Type</th>
                    <th>Download</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var app in Model.Apps)
                {
                    <tr>
                        <td>@app.AppName</td>
                        <td>@app.DevName</td>
                        <td>@app.Type</td>
                        <td><a asp-page="./Customer" asp-route-fileName="@app.AppFile" asp-route-handler="Download" class="btn btn-primary">Download</a></td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</body>
</html>

Online_App_store/Pages/Developer.cshtml
@page
@model Online_App_store.Pages.DeveloperModel
@{
    Layout = "Dev_Layout";
}

<form method="post" enctype="multipart/form-data" class="mt-4">
    <div class="mb-3">
        <label for="AppName" class="form-label">App Name:</label>
        <input type="text" id="AppName" name="App.AppName" class="form-control" required />
    </div>
    <div class="mb-3">
        <label for="DevName" class="form-label">Developer Name:</label>
        <input type="text" id="DevName" name="App.DevName" class="form-control" required />
    </div>
    <div class="mb-3">
        <label for="Type" class="form-label">Type:</label>
        <input type="text" id="Type" name="App.Type" class="form-control" required />
    </div>
    <div class="mb-3">
        <label for="AppFile" class="form-label">Choose a file:</label>
        <input type="file" id="AppFile" name="App.UploadedFile" class="form-control" required />
    </div>
    <button type="submit" class="btn btn-primary">Upload</button>
</form>

<h2>App List</h2>

<table class="table table-striped">
    <thead>
        <tr>
            <th>App Name</th>
            <th>Developer Name</th>
            <th>Type</th>
            <th>App File</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var app in Model.AppList)
        {
            <tr>
                <td>@app.AppName</td>
                <td>@app.DevName</td>
                <td>@app.Type</td>
                <td>@app.AppFile</td>
                <td>
                    <form method="post" asp-page-handler="Delete" asp-route-id="@app.Id">
                        <button type="submit" class="btn btn-danger">Delete</button>
                    </form>
                </td>
            </tr>
        }
    </tbody>
</table>

<!-- Include Bootstrap CSS -->
<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">

Online_App_store/Pages/Index.cshtml
@page
@model IndexModel

@{
}
<!-- Set the Background image and make it fill the page -->
 <style>
    body {
        background-image: url('https://images.pexels.com/photos/934063/pexels-photo-934063.jpeg?cs=srgb&dl=pexels-ylanite-koppens-934063.jpg&fm=jpg');
		background-repeat: no-repeat;
		background-size: cover;
		padding: 0,0,0;
		max-width: 100%;

/*      
        background-position: center center;
        margin: 0;
	    
        height: 100vh;   */

    }
</style>

<div style="height: 800px;">

@* <header>
<div class="mask" style="background-color: rgba(0, 0, 0, 0.6);">
    <div class="d-flex justify-content-center align-items-center h-100">
        <div class="text-white">
            <h1 class="mb-3">Clothy</h1>
                <h4 class="mb-3">Explore from various seller to find your desired product</h4>
                <form method="get" action="/Explore">
                    <button class="btn btn-outline-dark" type="submit">
                        Full Site
                    </button>
                </form>
        </div>
    </div>
</div>
</header> *@







        <div class="container d-flex align-items-center justify-content-center text-center h-100">
            <div>
            <h1 class="mb-3">APPjr</h1>
                <h4 class="mb-3">Sign Up now and brawse for apps or publish your own </h4>

            <a class="btn btn-dark" asp-page="/SignUp"><h2><span>SIGN</span>UP<span>NOW</span></h2></a>
            </div>
        </div>







    <style>

    body {
    background-color: #000;
    align-items: center;
    justify-content: center;
    min-height: 100vh;
    }

    h1 {
   
        font-size: 100px;
        font-weight: bold;
        font-family: monospace;
        letter-spacing: 7px;
        cursor: pointer;
    }
    h2 {
    color: hsl(0, 0%, 28%);
    font-size: 50px;
    font-weight: bold;
    font-family: monospace;
    letter-spacing: 7px;
    cursor: pointer;
    }

    h2 span {
    transition: 0.5s ease-out;
    }
    h2:hover span:nth-child(1) {
    margin-right: 15px;
    }
    h2:hover span:nth-child(2) {
    margin-left: 15px;
    } 

    h2:hover {
        color: #fff;
        text-shadow: 0 0 10px #fff, 0 0 20px #fff, 0 0 40px #fff;
    }
	</style>

</div>

       

Online_App_store/Pages/Login.cshtml
@page
@model LoginModel
@{
}

<style>
    body {
        background-image: url('https://mdbcdn.b-cdn.net/img/Photos/new-templates/search-box/img4.webp');
        background-repeat: no-repeat;
        background-size: cover;
        padding: 0,0,0;
        max-width: 100%;
    }
</style>

<div style="height: 800px;">
    <section class="vh-100 gradient-custom">
        <div class="container py-5 h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-12 col-md-8 col-lg-6 col-xl-5">
                    <div class="card bg-dark text-white" style="border-radius: 1rem;">
                        <div class="card-body p-5 text-center">

                            <form method="post">
                            <div class="mb-md-5 mt-md-4 pb-5">

                                <h2 class="fw-bold mb-2 text-uppercase">Login</h2>
                                <p class="text-white-50 mb-5">Please enter your login and password!</p>

                                <div class="form-outline form-white mb-4">
                                    <input type="email" id="typeEmailX" name="Email" asp-for="@Model.User.Email" class="form-control" />
                                    <label class="form-label" for="typeEmailX">Email</label>
                                </div>

                                <div class="form-outline form-white mb-4">
                                    <input type="password" id="typePasswordX" name="Password" asp-for="@Model.User.Password" class="form-control" />
                                    <label class="form-label" for="typePasswordX">Password</label>
                                </div>

                                <p class="small mb-5 pb-lg-2"><a class="text-white-50" href="#!">Forgot password?</a></p>

                                <button class="btn btn-outline-light btn-lg px-5" type="submit">Login</button>

                            </div>
                            </form>

                            <div>
                                <p class="mb-0">
                                    Don't have an account? <a asp-page ="/SignUp" class="text-white-50 fw-bold"> Sign Up</a>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

Online_App_store/Pages/SignUp.cshtml
@page
@model Online_App_store.Pages.SignUpModel
@{
}

<style>
    body {
        background-image: url('https://mdbcdn.b-cdn.net/img/Photos/new-templates/search-box/img4.webp');
        background-repeat: no-repeat;
        background-size: cover;
        padding: 0;
        margin: 0;
        max-width: 100%;
    }
</style>

<div style="height: 1000px;">
    <!-- Content goes here -->
    <section class="vh-100 gradient-custom">
        <div class="mask d-flex align-items-center h-100 gradient-custom-3">
            <div class="container h-100">
                <div class="row d-flex justify-content-center align-items-center h-100">
                    <div class="col-12 col-md-9 col-lg-7 col-xl-6">
                        <div class="card bg-dark text-white" style="border-radius: 1rem;">
                            <div class="card-body p-5">
                                <h2 class="text-uppercase text-center mb-5">Create an account</h2>

                                <form method="post">
                                    <div class="form-outline mb-4">
                                        <input type="text" id="form3Example1cg" name="User.Name" asp-for="@Model.User.Name" class="form-control" />
                                        <label class="form-label" for="form3Example1cg">Your Name</label>
                                    </div>
                                    <div class="form-outline mb-4">
                                        <input type="email" id="form3Example3cg" name="User.Email" asp-for="@Model.User.Email" class="form-control" />
                                        <label class="form-label" for="form3Example3cg">Your Email</label>
                                    </div>
                                    <div class="form-outline mb-4">
                                        <input type="tel" id="form3Example5cdg" name="User.PhoneNumber" asp-for="@Model.User.PhoneNumber" class="form-control" />
                                        <label class="form-label" for="form3Example5cdg">Phone Number</label>
                                    </div>
                                    <div class="form-outline mb-4">
                                        <input type="password" id="form3Example4cg" name="User.Password" asp-for="@Model.User.Password" class="form-control" />
                                        <label class="form-label" for="form3Example4cg">Password</label>
                                    </div>
                                    <div class="form-outline mb-4">
                                        <input type="password" id="form3Example4cdg" name="User.ConfirmPassword" asp-for="@Model.User.ConfirmPassword" class="form-control" />
                                        <label class="form-label" for="form3Example4cdg">Repeat your password</label>
                                    </div>
                                    <div class="form-outline mb-4">
                                        <select class="form-select" id="userType" name="User.Type" asp-for="@Model.User.Type">
                                            <option value="developer">Developer</option>
                                            <option value="customer">Customer</option>
                                        </select>
                                        <label class="form-label" for="userType">Select User Role</label>
                                    </div>
                                    <div class="d-flex justify-content-center">
                                        <button type="submit" class="btn btn-success btn-block btn-lg gradient-custom-4 text-body">Register</button>
                                    </div>
                                    <p class="text-center text-muted mt-5 mb-0">
                                        Already have an account? <a asp-page="/Login" class="text-white-50 fw-bold"><u>Login here</u></a>
                                    </p>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

@{
    ViewData["Title"] = "Sign Up";
}